### ISSUE TITLE
Input files to process_data.sh missing (case 2)

### ISSUE THREAD

**Issue by ltorada** [FunctionLab/selene#103]
The selene/manuscript/case2/download_data.sh script downloads the output we would obtain after running selene/manuscript/case2/1_train_with_online_sampler/data/process_data.sh with missing input files (chromatin_profiles/*).

It would be very helpful if you could provide those input files (so that the mentioned process_data.sh script could be executed, reproducing the outputs that you already provide with download_data.sh). This would help to check the required formats for using different datasets.

Many thanks!

**Comment by kathyxchen** [comment]
Ah, so these are only mentioned in case 1. I'll make a note to improve the documentation during the next release. 

https://github.com/FunctionLab/selene/blob/master/manuscript/case2/download_data.sh#L15

**Comment by ltorada** [comment]
Thanks, but it is the process_chromatin_profiles.py within process_data.sh in case 2 what I'm interested in running. I think this is not covered in case 1.

**Comment by kathyxchen** [comment]
@ltorada I updated my comment, hope that helps

**Comment by ltorada** [comment]
My bad... I didn't spotted that. Thanks!
