### ISSUE TITLE
Using protein sequences with Selene

### ISSUE THREAD

**Issue by ashishjain1988** [FunctionLab/selene#104]
Can we use selene for protein classification using protein sequences and their properties? Can we also in some way integrate this with the genomic sequencing data in some way?

**Comment by kathyxchen** [comment]
We haven't had anyone use Selene for protein sequences yet. It might work out-of-the-box or with some minor updates, but it strongly depends on your specific use case. Would be happy to discuss and see if we can make it happen in a reasonable amount of time - can I redirect you to our google groups to continue the discussion?  https://groups.google.com/forum/#!forum/selene-sdk
can also correspond via e-mail if you prefer

I'll likely update this issue or create new issues based on what we talk about there.

**Comment by ashishjain1988** [comment]
Thank you for the response. Actually, I am just checking about it for our future use which might involve protein and RNA-Seq data.
