### ISSUE TITLE
Naive question about quickstart_training.ipynb

### ISSUE THREAD

**Issue by shusen18** [FunctionLab/selene#107]
Hi,

Thanks for developing this package. Its very useful for me.

I install the selene using "conda install -c bioconda selene-sdk", and run the https://github.com/FunctionLab/selene/blob/master/tutorials/quickstart_training/quickstart_training.ipynb, however, the evaluate part did not run. 

https://github.com/FunctionLab/selene/blob/master/tutorials/quickstart_training/simple_train.yml and the raw data are used, and I did not modify anything.

2018-12-09 21:10:54,668 - Creating test dataset.
2018-12-09 21:12:04,384 - 69.71443819999695 s to load 120000 test examples (1875 test batches) to evaluate after all training steps.
2018-12-09 21:22:27,041 - test roc_auc: 0.9708799938145076
2018-12-09 21:22:27,044 - test average_precision: 0.49939594405677223

These results and the two pictures are did not show.

would you like to tell me how to get the test results properly? 

Thank you very much.

Yours sincerely,
Shusen

**Comment by evancofer** [comment]
@shusen18 It looks like there was a silent bug in `config_utils.py` where the `EvaluateModel` was only being executed if `evaluate_model` had been explicitly specified in the configuration file. I just submitted PR #110 to fix this problem. If you used conda to install selene, you will probably have to re-install selene from source using master once this PR has been merged. With the fix, model evaluation should occur after training, and you should get the files `precision_recall_curves.svg` and `roc_curves.svg` in the `training_outputs` directory after model evaluation completes.

**Comment by shusen18** [comment]
@evancofer Thank you very much！
The problem is solved.
