### ISSUE TITLE
Questions about running case 2 on personal data. 

### ISSUE THREAD

**Issue by kakorgao** [FunctionLab/selene#112]
1. In Step 1 of case 2, to train a new architecture are we allowed to choose which way we can do it (using .mat or .bed) or do we need to do both of them?

2. Assuming that in step 1 we choose how to train the architecture (I’m currently only training on my personal .bed file), can I still use the deepsea_test.mat file if I trained it with a .bed file and if I’m using my personal data?

**Comment by kathyxchen** [comment]
Closed, please reopen if needed
