### ISSUE TITLE
only support CUDA version <9.0.

### ISSUE THREAD

**Issue by carol007** [FunctionLab/selene#121]
I use pytorch1.2 with CUDA>=9.2  and when use`conda install -c bioconda selene-sdk` in pytorch env,cudatoolkit will be downgreaded to 9.0.

**Comment by kathyxchen** [comment]
Thanks - I'll look into this. Are you able to manually upgrade cuda and use selene that way? Otherwise it's probably something with the bioconda config that we need to update

**Comment by kathyxchen** [comment]
One more question - what version of selene gets installed with that command?

**Comment by kathyxchen** [comment]
Closed. Please reopen if needed
