### ISSUE TITLE
Fix YAML documentation for `metrics` configuration parameter in `train_model`

### ISSUE THREAD

**Issue by kathyxchen** [FunctionLab/selene#125]
Thanks @bmacedo-lgtm for catching this issue: 

it turns out that the YAML parser we are using will only accept a single custom metrics function with the present syntax described in the Selene CLI docs.

```
metrics: {
     roc_auc: !import:sklearn.metrics.roc_auc_score,
     average_precision: !import:sklearn.metrics.average_precision_score
 },
```

that is, the above snippet that is described in our docs will crash because the parser expects every `!import:<method/module>` tag to come with a dictionary of input arguments, even if the dictionary is empty.

It seems like Selene will run with no errors if I just modify this to
```
metrics: {
     roc_auc: !import:sklearn.metrics.roc_auc_score {},
     average_precision: !import:sklearn.metrics.average_precision_score {}
 },
```
but more testing is needed to better characterize and handle this bug.

**Comment by jzthree** [comment]
I actually just used `!import` tag recently. Not sure if it is related but the syntax that worked was somewhat different - like ```!import 'sklearn.metrics.roc_auc_score'```.

This is the way it was used in the tutorial for the YAML parser of selene http://deeplearning.net/software/pylearn2/yaml_tutorial/index.html

**Comment by kathyxchen** [comment]
Oh that is helpful! Thanks @jzthree. Yeah so our documentation is wrong then. You're able to pass in multiple metrics with just the `!import` tag then right?

**Comment by jzthree** [comment]
Yes I tested this
```
    metrics: {
        roc_auc: !import 'sklearn.metrics.roc_auc_score',
        average_precision: !import 'sklearn.metrics.average_precision_score'
    },

```
(the quote is not necessary when I tested).

It passed parsing stage and `print(metrics)` gives:
```
{'roc_auc': <function roc_auc_score at 0x2aab0e58bc80>, 
'average_precision': <function average_precision_score at 0x2aab0e58bbf8>}
```

**Comment by kathyxchen** [comment]
does that mean `roc_auc: !import sklearn.metrics.roc_auc_score`
works fine too?

great! so I'll just update the docs to match this :)

**Comment by jzthree** [comment]
yes `roc_auc: !import sklearn.metrics.roc_auc_score` works too : )
