### ISSUE TITLE
In CASE1 Unresolved reference '_genomic_features' , Unresolved reference '_sequence'

### ISSUE THREAD

**Issue by yinuolb** [FunctionLab/selene#151]
I have run `python  setup.py build_ext --inplace`  but the '_sequence' and _genomic_features still have error

**Comment by kathyxchen** [comment]
For questions about running Selene, please join our Google groups: https://groups.google.com/forum/#%21forum/selene-sdk

Happy to help you there, can you mention your Cython version and environment details when you make a post? Thank you :)
