### ISSUE TITLE
Documentation Formatting

### ISSUE THREAD

**Issue by mmingay** [FunctionLab/selene#155]
First of all thanks for building this great library. 

I just wanted to let you know that the documentation at https://selene.flatironinstitute.org/ seems to have some formatting issues.

<img width="518" alt="doc_screenshot" src="https://user-images.githubusercontent.com/57153190/96904124-887e1880-144b-11eb-8917-c5c1bae6f1dd.png">

Matt

**Comment by kathyxchen** [comment]
Oh, no! Thanks very much for raising this issue, I'll look into this ASAP...
