### ISSUE TITLE
Prediction yaml file for Seqweaver

### ISSUE THREAD

**Issue by vagarwal87** [FunctionLab/selene#157]
Hi, I am interested in using the Seqweaver pre-trained model to generate predictions on just an input fasta file of RNA sequences (with no saturation mutagenesis), but was struggling a little bit. This was my YAML file:

> ---
> ops: [analyze]
> model: {
>     path: /home/vagar/SeqWeaver/code_asd_dnarna_v3/models/seqweaver/seqweaver.py,
>     class: Seqweaver,
>     class_args: {
>         n_classes: 43
>     }
> }
> analyze_sequences: !obj:selene_sdk.predict.AnalyzeSequences {
>     sequence_length: 1000,
>     batch_size: 128,
>     trained_model_path: /home/vagar/SeqWeaver/code_asd_dnarna_v3/models/seqweaver/mouse_seqweaver.pth,
>     features: !obj:selene_sdk.utils.load_features_list {
>         input_path: /home/vagar/SeqWeaver/code_asd_dnarna_v3/models/seqweaver/data.mm10.colnames
>     },
>     use_cuda: False,
>     write_mem_limit: 10000
> }
> prediction: {
>     input_path: /home/vagar/SeqWeaver/code_asd_dnarna_v3/test.fa,
>     output_dir: /home/vagar/SeqWeaver/code_asd_dnarna_v3/test_output,
>     output_format: tsv
> }
> random_seed: 999
> ...

In python, I run this command and get the following error:

> >>> parse_configs_and_run(load_path("configs/mouse_seqweaver_fromSeq.yml", instantiate=True)) #YML is the file above
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/vagar/anaconda3/lib/python3.7/site-packages/selene_sdk/utils/config_utils.py", line 341, in parse_configs_and_run
>     execute(operations, configs, current_run_output_dir)
>   File "/home/vagar/anaconda3/lib/python3.7/site-packages/selene_sdk/utils/config_utils.py", line 247, in execute
>     analyze_seqs.get_predictions(**predict_info)
> TypeError: get_predictions() got an unexpected keyword argument 'input_path'

Any idea what might be going on? Am I doing something wrong in the YAML?

One more question if you happen to know: Is Seqweaver trying to predict CLIP binding to the central 50nt of a sequence given a 1000nt window context, or is it trying to predict the probability that the full 1000nt input window is likely to possess a CLIP peak somewhere in the entire sequence?

Thank you for your help!
Vikram

**Comment by kathyxchen** [comment]
Hi Vikram, thanks so much for your post. This is actually a known bug with the latest release of Selene, sorry about that! https://github.com/FunctionLab/selene/commit/2fb66df18411a224487a7ad954e81649762e213c#diff-f7e2ff8a7383f263b4715c9694f0e90893327cbcf8d06e4e4d7a6563e80b03e0L526
You can change the variable from `input_path` to `path` and it should work - alternatively, you can use the `master` branch of this repository (locally building and installing the library) and you can use `input_path` as expected. 

To answer your other question - Seqweaver predicts for the center 50nt given a 1000nt window context, yes. (The CLIP peak has to overlap with at least 50% of the 50nt center bin)

**Comment by vagarwal87** [comment]
Thank you for the response!

However, my file matches your master file from the link you sent above, and is also version 0.4.8 as I just installed it last week (my get_predictions has input_path not path). I tried your recommendation anyways but it failed with the identical error more or less.

**Comment by kathyxchen** [comment]
Oh, I didn't read my code clearly - actually you need to change `input_path` to `input`, NOT `path` for it to work.

Though for me, if I roll back my master branch the fix I just described works, and with master `input_path` works as expected. Judging by your error message, you might be using 0.4.8 from the conda installation which isn't the same as the master branch (which needs to be locally built and installed via `python setup.py --install`, since we haven't released another version yet)

**Comment by vagarwal87** [comment]
Thank you, you are correct on both accounts: "input" fixed my issue, and also I was using the conda install. Thanks for pointing out it is different than github main branch. I'll go ahead and close this out now that it works fine, appreciate your help!
