### ISSUE TITLE
Bugs checking for learning rate during config parsing

### ISSUE THREAD

**Issue by rfriedman22** [FunctionLab/selene#167]
There are two bugs related to parsing the learning rate from configs:

1. The if statements in [these lines](https://github.com/FunctionLab/selene/blob/master/selene_sdk/utils/config_utils.py#L306-L312) check if `lr != "None"` but not `lr != None`. Note the lack of quotes in the second example -- the default value in the function is `None` and not `"None"`.
2. There should be a check for the case where `"train" in operations and "lr" not in configs and lr == None`, i.e. the learning rate has not been specified at all. Currently the model will begin fitting even though there's no learning rate.

**Comment by kathyxchen** [comment]
Thanks @rfriedman22 for these catches - do you want to submit a PR for these fixes?

**Comment by rfriedman22** [comment]
Sure @kathyxchen, I'll make these fixes shortly and submit a pull request!
