### ISSUE TITLE
AnalyzeSequences bug due to Genome object

### ISSUE THREAD

**Issue by rfriedman22** [FunctionLab/selene#178]
[This line](https://github.com/FunctionLab/selene/blob/477ad5d82bf39b7a5b662ec311fd5df0685ab12b/selene_sdk/predict/model_predict.py#L176) of code in `AnalyzeSequences` raises the following error:
`AttributeError: type object 'Genome' has no attribute '_initialized'`

The error appears to be because the default value, `Genome`, is not initialized when the init function is called for `AnalyzeSequences` and appeared in version 0.5.0. The issue doesn't occur in version 0.4.8.

I'm not sure how to handle the error because constructing a `Genome` object requires passing in the path to a file, but a file may not always be necessary, e.g. when calling the function `AnalyzeSequences.get_predictions_for_fasta_file`.

**Comment by jzthree** [comment]
Thanks for finding this bug! I think we should remove these two lines.

```
        if not self.reference_sequence._initialized:
            self.reference_sequence._unpicklable_init()
```

Here because it only uses the Genome class and its class methods, not an Genome object, it does not have attribute `_initialized` and does not need to run  `_unpicklable_init()`.

**Comment by rfriedman22** [comment]
That makes sense! I can fix it and open a PR.

**Comment by kathyxchen** [comment]
LGTM, thanks Ryan!
