### ISSUE TITLE
TypeError: get_predictions() got an unexpected keyword argument 'input_path'

### ISSUE THREAD

**Issue by WeiCSong** [FunctionLab/selene#186]
Hi,
I tried to run seqweaver on .fa input with the following Selene yml:

>ops: [analyze]
>model: {
    path: /lustre/home/acct-bmelgn/bmelgn-3/deepsea/models/seqweaver/seqweaver.py,
    class: Seqweaver,
    class_args: {
        n_classes: 217
    }
}
analyze_sequences: !obj:selene_sdk.predict.AnalyzeSequences {
>    trained_model_path: /lustre/home/acct-bmelgn/bmelgn-3/deepsea/models/seqweaver/human_seqweaver.pth,
>   sequence_length: 1000,
>    features: !obj:selene_sdk.utils.load_features_list {
>        input_path: /lustre/home/acct-bmelgn/bmelgn-3/deepsea/models/seqweaver/data.hg19.colnames 
>    },
>    batch_size: 128,
>    use_cuda: False,
>    write_mem_limit: 5000
>    
>}
>prediction: {
>    output_format: hdf5
>}
>random_seed: 123
>...

and when i ran `run_config("configs/seqs_fasta.yml")`, I got:

> Traceback (most recent call last):
  File "fasta_cli.py", line 44, in <module>
    run_config("configs/seqs_fasta.yml")
  File "fasta_cli.py", line 42, in run_config
    parse_configs_and_run(configs)
  File "/lustre/home/acct-bmelgn/bmelgn-3/miniconda3/envs/deepsea/lib/python3.6/site-packages/selene_sdk/utils/config_utils.py", line 341, in parse_configs_and_run
    execute(operations, configs, current_run_output_dir)
  File "/lustre/home/acct-bmelgn/bmelgn-3/miniconda3/envs/deepsea/lib/python3.6/site-packages/selene_sdk/utils/config_utils.py", line 247, in execute
    analyze_seqs.get_predictions(**predict_info)
TypeError: get_predictions() got an unexpected keyword argument 'input_path'

I think input_path is a necessary parameter in selene, and I have no idea why it said it was unexpected. Do you have any suggestion on this issue? Thank you very much for your help.

**Comment by kathyxchen** [comment]
resolved via email!
