### ISSUE TITLE
Does selene work with any genome?

### ISSUE THREAD

**Issue by mariakmejiaguerra** [FunctionLab/selene#50]
I am wondering if is possible to start using selene to train models for others organisms. I work in plants, and have been developing ML/Deep learning models for genome sequence data. However, looking at how far you guys are, I would rather collaborate or build on top of what you have already done.

Thanks,

**Comment by evancofer** [comment]
It should be fine as long as it's in a FASTA file and uses the 4 standard base pairs (mix of uppercase and lowercase is fine) and 'N' for unknown bases. Depending on your classification task, you may be able to just use the DeepSEA model included in selene and just adjust the output size for your number of predicted features.

**Comment by mariakmejiaguerra** [comment]
Great news, I am going to give it a try to your suggestion!

Thanks
