### ISSUE TITLE
Make loading a model architecture/optimizer/loss from file more robust

### ISSUE THREAD

**Issue by kathyxchen** [FunctionLab/selene#54]
Currently, the way we load these components does not always work (I am in the process of figuring out why this is the case). We have been trying to load the model architecture file by appending the parent path to `sys.path`, which is also not a great solution to things in general. Will look for an alternative that provides more consistent behavior and hopefully does not require adding to the path variable.

**Comment by kathyxchen** [comment]
It looks like the main issue currently is that you need an `__init__.py` file (it can be blank) in the same directory as your model architecture file. That is, the way we implement it now, Python expects that it imports the architecture from a module.

Furthermore, if you are planning to import other custom classes/methods in your model architecture file, please make sure it is a relative import (e.g. `from .non_strand_specific import NonStrandSpecific`). Those files should be in the same directory as your model arch file or within some  valid Python module/package structure. 

If after some investigation of this issue we decide not to make any changes, I will update the documentation in various places (e.g. tutorials, docs website) with the above information.

**Comment by kathyxchen** [comment]
Thanks @evancofer! I think I actually had this implementation (something very similar at least) in a previous version of Selene and ended up switching to the current one because I had some architectures that were within a module, and this method wouldn't handle relative imports. 

That said, importing outside a module is definitely the more common use case, so I'm thinking we will use `model_class_from_path` by default and then have some flag a user can set for the "importing from module" case if they are using more complicated architectures.

**Comment by evancofer** [comment]
You could probably do that by checking if the string ends in `*.py` or not.
