### ISSUE TITLE
Memory usage variant effect prediction

### ISSUE THREAD

**Issue by mrtnb** [FunctionLab/selene#66]
I am using the selene CLI to predict variant effects and adapted the configuration file (analyze_seqs.yml) from the variants_and_visualizations tutorial. It works fine for VCF files up to a certain size but a memory limit of 32GB was exceeded for a VCF with ~1.4 mio variants after about 30 min of run time with CUDA on a Tesla V100. The output files generated (_diffs.tsv, _logits.tsv, _predictions.[alt|ref]) are all 0 bytes. So I assume all predictions are stored in memory and are only written to disk once the whole set is completed. If this behavior cannot be changed then the effect prediction wouldn't scale very well for large sets of variants.

Maybe I'm missing something, but is there a configuration option for memory usage of variant effect prediction or an option to limit the number of results stored in memory before they are written to disk?

**Comment by kathyxchen** [comment]
Thanks @mrtnb! Yes, we have noticed this - there is no configuration option yet but I am planning to add this to my current PR #65, which contains some significant changes to variant effect prediction (including writing to HDF5 files to make it faster). You are welcome to wait and use the next update to master once this PR is merged (I think sometime next week is doable), or a temporary fix would be to split your input variants file into multiple files for the time being.

(To answer your question about when the predictions are written to file: I believe currently it accumulates predictions for 200k variants before writing them to a .tsv file.)

Please let me know if I need to clarify things further, or if you have other related issues to discuss! Thanks again.

**Comment by kathyxchen** [comment]
I have pushed PR #65 which should have a new parameter `write_mem_limit` that you can set in the `analyze` configuration. Please let me know if you get a chance to try it out - I'll leave this issue open for another week or so and then resolve it if it seems like this PR addresses it sufficiently.
