### ISSUE TITLE
GPU Card Recommendations for Desktop Computers

### ISSUE THREAD

**Issue by oriolfornes** [FunctionLab/selene#68]
Hi, I was doing the tutorials on my desktop computer (i7 architecture, 64GB of ram and no GPU), and the DeeperDeepSEA training of CTCF on GM12878 cells takes forever (I set `use_cuda=False`).

I wonder whether you have a list of GPU cards that you would recommend for desktop computers, or at least a minimum requirement of CUDA cores and memory for GPUs.

Thank you in advance!

**Comment by kathyxchen** [comment]
Hi! Thanks for your question.

If you'd like to continue running the tutorials on a desktop with no GPU, I'd recommend making the architecture smaller (e.g. reducing the number of layers or replacing it entirely with a very simple model). Of course, in the long run, it definitely makes sense to get a CUDA-enabled GPU to train your own models. 

I don't have any specific recommendations (@evancofer might have some?), but you should consider the size of your model architecture (how many layers/parameters) and the amount of training data you have when selecting a GPU. For example, we can train DeepSEA in <1 week on a single 32GB GPU with a few hundred CUDA cores. The amount of memory used on the GPU during training is dependent on your batch size - if your batch size is small and your input data not too large, you could do just fine on a smaller GPU with less memory and fewer cores. (e.g. I can train larger architectures (>20 convolutional layers) on a 16GB GPU with a small batch size.)

**Comment by datduong** [comment]
Is there a way to specify the number of GPUs to be used? By default, the code takes up all the GPUs on the server. 

Thanks.
