### ISSUE TITLE
Can we integrate different histone modifications ChIP-Seq datasets?

### ISSUE THREAD

**Issue by ashishjain1988** [FunctionLab/selene#87]
Hi,
I am new to your tool and after going through your case studies I got a general overview of the framework. I just want to ask can I supply peaks from different histone modifications ChIP-Seq (like H3K27ac, H3K9ac) as features for a particular tissue and then use them to train the model?

**Comment by kathyxchen** [comment]
Yes, you can supply your own data as long as it is compiled and formatted to match the [expected input](https://github.com/FunctionLab/selene/blob/master/tutorials/getting_started_with_selene/getting_started_with_selene.ipynb).

**Comment by ashishjain1988** [comment]
Thank you @kathyxchen for the reply!! I have only more regarding the first case study (GATA1 ChIP data). The peak data provided and processed in the first case study doesn't have uniform sequence length as in DeepSEA case(1000 bp regions centered around 200 bp target region), but still, the sequence length is given as 1000. Is it correct and how do you guys select that particular sequence length (1000) in this case?

**Comment by kathyxchen** [comment]
You are talking about the peaks BED file right? The size of the peaks doesn't inform the sequence length choice of 1000bp, though it may inform the selection of the 200bp target region. 

1000bp was chosen to provide a large sequence context surrounding the center target region. 

Target region size should be selected based on peak size. That is, when creating our input data, we label every 1000bp sequence based on whether or not 50% of a peak for a given feature is present in the center 200bp target region. This assumes that most of your peaks are at least 100bp in size. 

You can select larger sequence contexts (as publications after DeepSEA have chosen to do so - for example, in the model underlying [ExPecto](10.1038/s41588-018-0160-6) the sequence length is 2000bp) as larger sequence contexts generally show better performance in this setting. Usually the limitation for sequence context is how much memory your GPU has (i.e. how large of a model can you load onto your GPU and train). 

Let me know if you need more clarification on a particular part! Thanks

**Comment by ashishjain1988** [comment]
Thank you for the detailed explanation!! I have some more questions regarding that. Is the processing is carried out by selene (creating the input tensor from the peak file)?
And in the train_model class is the "max_steps" equivalent to epoch or mini-batch iteration?

**Comment by kathyxchen** [comment]
Yes, the sampler in Selene processes the input data and creates the input tensor. Max steps is mini-batch iteration - there's no concept of epochs in Selene currently; rather you can set `report_stats_every_n_steps` to be the equivalent of whatever your epoch should be, if desired. `max_steps x batch_size` = total number of samples seen by the model in the whole course of training

**Comment by ashishjain1988** [comment]
@kathyxchen Thank you for the information!!
