### ISSUE TITLE
error while running selene_cli.py

### ISSUE THREAD

**Issue by gouthamatla** [FunctionLab/selene#92]
Hi All,

I installed selene using pip on python 3.7. I could run the following command without errors:

`python -c 'from selene_sdk.utils import parse_configs_and_run'  `

But when I try to run the `selene_cli.py`, I am getting the following error. 
```
python /data2/selene/selene_cli.py /data2/selene/manuscript/case1/1_train_and_evaluate/train_and_eval.yml --lr=0.01                                      
Traceback (most recent call last):
  File "/data2/selene/selene_cli.py", line 21, in <module>
    from selene_sdk.utils import load_path
  File "/data2/selene/selene_sdk/__init__.py", line 8, in <module>
    from .evaluate_model import EvaluateModel
  File "/data2/selene/selene_sdk/evaluate_model.py", line 12, in <module>
    from .sequences import Genome
  File "/data2/selene/selene_sdk/sequences/__init__.py", line 4, in <module>
    from .sequence import Sequence
  File "/data2/selene/selene_sdk/sequences/sequence.py", line 11, in <module>
    from ._sequence import _fast_sequence_to_encoding
ModuleNotFoundError: No module named 'selene_sdk.sequences._sequence'
```

I guess its unable to find modules inside /data2/selene/selene_sdk/ for some reason. Should I export path ?

**Comment by kathyxchen** [comment]
Did you build the repository? `python setup.py build_ext --inplace`. 

If so, you're right that it might be a path issue?

**Comment by gouthamatla** [comment]
Thanks for quick response.  I thought `pip install selene-sdk` should be enough. I did `python setup.py build_ext --inplace` and seems to be working.
