### ISSUE TITLE
Suggested number of steps

### ISSUE THREAD

**Issue by ymkng** [FunctionLab/selene#96]
the tutorial states that " typically the number of steps is much higher" than 16000. I was wondering what is a typical or suggested number of steps to train a model that predicts the binding sites of 85 transcription factors (targets).

thanks!

Michelle

**Comment by kathyxchen** [comment]
Number of samples your model will see in training is going to be steps x batch_size.

You should select steps and batch size based on how many samples you want to train your model on. This could be on the order of millions. You can always start off small and monitor training too - if it looks like the model is still improving then you can start from a checkpoint and resume training with more steps

**Comment by kathyxchen** [comment]
Can this be closed?
