### ISSUE TITLE
Input for "case1" - peak length

### ISSUE THREAD

**Issue by gouthamatla** [FunctionLab/selene#97]
Hi All,

I am running the "case1" of the manuscript, but on my own peaks of interest from a tissue specific TF.
In the example file for GATA1, I could see that the "GATA1_proery_bm.bed.gz" has 203,449 peaks with median length of 215bp (Q1=175bp, mean=245bp, Q3=272bp).

I am wondering if I should split the peaks into smaller chunks before running selene_cli.py ?

Thanks,
Goutham A

**Comment by kathyxchen** [comment]
It sounds like you can just change your bin size / features threshold for the training data labels?

**Comment by gouthamatla** [comment]
Thanks, are you referring to these parameters ?  `sequence_length: 1000, center_bin_to_predict: 200,  feature_thresholds: 0.5,`. This means the model always considers 200bp at the center with +/-500 bp ? Could you explain what do they refer to ?

**Comment by kathyxchen** [comment]
With +/- 400 bp since the sequence length total is 1000. Feature threshold means you need 50% of the center 200bp to be covered by a peak in the bed file for it to be considered a label of that sequence. Please refer to http://selene.flatironinstitute.org/overview/cli.html
